### PR TITLE
Added script to fix dataset

### PR DESCRIPTION
**Pull request by ramadhanaraz**
Script to fix yolo dataset format

### CODE REVIEW

**Comment by ramadhanaraz** [comment]
Woy ngentiaw acc pr gw

**Comment by figaz123** [comment]
all good

**Comment by ramadhanaraz** [comment]
> all good

All good all good doang kaga di review :/

**Review by figaz123 — COMMENTED** [review]
lgtm

**Review by figaz123 — APPROVED** [review]
approved

**Pull request merged**
